### ISSUE TITLE
[Bug] Unexpected token import

### ISSUE THREAD

**Issue by patrickml** [Izhaki/nodemon-webpack-plugin#1]
When trying to use the `nodemon-webpack-plugin` I am receiving an `unexpected token import` If I run the dist file manually everything works out just fine, so that should rule out something going wrong with babel + webpack on its own. So I'm not exactly sure what I may have done wrong here

```
Patricks-MacBook-Pro-2:server patricklewis$ npm run start

> tower-server@0.0.1 start /Users/patricklewis/Documents/sites/personal/tower/server
> webpack --watch


Webpack is watching the files…

Hash: 70418b909aacddc6be28
Version: webpack 3.4.1
Time: 1084ms
   Asset     Size  Chunks             Chunk Names
index.js  24.5 kB       0  [emitted]  main
   [0] ./src/sockets/teams/list.js 435 bytes {0} [built]
   [1] multi ./src/index.js 28 bytes {0} [built]
   [2] ./src/index.js 504 bytes {0} [built]
   [3] ./src/server.js 485 bytes {0} [built]
   [6] ./src/socket.js 305 bytes {0} [built]
   [8] ./src/sockets/index.js 915 bytes {0} [built]
   [9] ./src/sockets/teams/index.js 930 bytes {0} [built]
  [10] ./src/sockets/teams/enter.js 337 bytes {0} [built]
  [11] ./src/sockets/teams/create.js 435 bytes {0} [built]
  [12] ./src/sockets/join/index.js 509 bytes {0} [built]
  [13] ./src/sockets/join/get.js 519 bytes {0} [built]
  [14] ./src/sockets/messages/index.js 562 bytes {0} [built]
  [15] ./src/sockets/messages/send.js 755 bytes {0} [built]
    + 4 hidden modules
[ Nodemon ] Started: dist/index.js
/Users/patricklewis/Documents/sites/personal/tower/server/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import { server } from 'server';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
[ Nodemon ] Crashed: dist/index.js
^CPatricks-MacBook-Pro-2:server patricklewis$ node dist/index.js
Starting Server
```

**Comment by Izhaki** [comment]
That's odd, but at least the trace suggests what may have gone wrong:

- `[ Nodemon ] Started: dist/index.js` - means that the plugin recognise `dist/index.js` is the output file.
- `node dist/index.js` works.

Yet, the crash happens on `/Users/patricklewis/Documents/sites/personal/tower/server/src/index.js:1`. Which, living in the `src` folder, I assume is an ES6 source that hasn't been transpiled, and thus node throws `Unexpected token import`.

This looks suspicious:

```shell
> tower-server@0.0.1 start /Users/patricklewis/Documents/sites/personal/tower/server
> webpack --watch
```
What's tower-server? Are you sure it isn't the one throwing the error? If you just add to the scripts section in your `package.json`:

    "watch": "webpack --watch"

then run:

    $ npm run watch

Will it still crash?

**Comment by patrickml** [comment]
Tower server is the name of the app within the package.json file and running webpack and watch without the plugin works perfectly fine. It's only once the plugin is enabled that I have this issue. The output from the build doesn't contain imports only requires. So for some reason something is trying to read the index file from source?

**Comment by patrickml** [comment]
Looks my at the package source I'm not seeing anything standout

**Comment by Izhaki** [comment]
So `"watch": "webpack --watch"` (with the plugin) still throws an error? 

The easiest way to for me to probe into this would be to clone the repository.

Failing that, posting `webpack.config.js` and `package.json` would be a reasonable starting point.

**Comment by Izhaki** [comment]
Any updates?

Note there's a new version (0.1.2) - might solve the issue.

**Comment by Izhaki** [comment]
Closing due to in activity.
