### ISSUE TITLE
Does not work when use --mode attribute

### ISSUE THREAD

**Issue by sionzeecz** [Izhaki/nodemon-webpack-plugin#24]
Script in npm:

    "dev": "webpack --watch --config webpack.config.js --mode development",

Webpack configuration:

    const NodemonPlugin = require( 'nodemon-webpack-plugin' )
    ...
    plugins: [new NodemonPlugin()]

After script run:

	\node_modules\nodemon-webpack-plugin\dist\webpack-utils.js:12
	  var absoluteFileName = asset.existsAt;
								   ^

	TypeError: Cannot read property 'existsAt' of undefined
		at getOutputFileMeta (\node_modules\nodemon-webpack-plugin\dist\webpack-utils.js:12:32)
		at OnAfterEmit (\node_modules\nodemon-webpack-plugin\dist\index.js:31:36)
		at AsyncSeriesHook.eval [as callAsync] (eval at create (d\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
		at AsyncSeriesHook.lazyCompileHook (\node_modules\tapable\lib\Hook.js:154:20)
		at asyncLib.forEach.err (\node_modules\webpack\lib\Compiler.js:354:27)
		at \node_modules\neo-async\async.js:2825:7
		at Object.each (\node_modules\neo-async\async.js:2853:9)
		at emitFiles (\node_modules\webpack\lib\Compiler.js:311:13)
		at \node_modules\mkdirp\index.js:48:26
		at FSReqCallback.oncomplete (fs.js:162:5)
	npm ERR! code ELIFECYCLE

When --mode is removed then the plugin is working right.

versions:

    "nodemon-webpack-plugin": "^4.0.6",
    "webpack": "^4.26.1",
    "webpack-cli": "^3.1.2"

Node: v11.2.0
NPM: 6.4.1

**Comment by Izhaki** [comment]
Odd.

```
const absoluteFileName = asset.existsAt;
```

`asset` seems to be undefined.

I can try to reproduce it, but would help if you can provide a repo?

**Comment by Izhaki** [comment]
I've just launched all tests with webpack in Development mode and they all pass.

Still doesn't mean there's something wrong with the plugin - but I suspect it's a very specific webpack config.

I'd need a way to reproduce this to progress. Possibly just your `webpack.config.js` will do but preferably a repo.

Thanks!

**Comment by sionzeecz** [comment]
Hey, I can do it later. I have a lot of work right now. 
I have got an idea. Can not it be due Windows?

Anyway the config is simply. I do not think it does something from the config. 
I will try to do repo later today. I had to do workaround with node_env variable and set the mode inside config instead of command line.

**Comment by nitwhiz** [comment]
I had the same problem on linux, with `--mode=development`.

Reason was it wasn't able to read the file defined as `entry` in my webpack.config.js

But running `webpack` without `--mode=development` warns you about the missing mode but tells you it can't find the file.

**Comment by Izhaki** [comment]
How come all works with --mode removed for @sionzeecz?

**Comment by Izhaki** [comment]
I'm closing this for inactivity. 

Will be more than happy to re-open once I can reproduce.
